import {
  FaArrowRight,
  FaBriefcase,
  FaBuilding,
  FaCalendarAlt,
  FaChevronDown,
  FaCss3Alt,
  FaDatabase,
  FaDocker,
  FaDownload,
  FaEnvelope,
  FaExternalLinkAlt,
  FaGitAlt,
  FaGithub,
  FaHtml5,
  FaJava,
  FaJs,
  FaLinkedin,
  FaMapMarkerAlt,
  FaMoon,
  FaNodeJs,
  FaPython,
  FaReact,
  FaStar,
  FaSun,
  FaTerminal,
} from 'react-icons/fa';
import { FaXTwitter } from 'react-icons/fa6';
import {
  SiAwslambda,
  SiC,
  SiCplusplus,
  SiDotnet,
  SiGithubactions,
  SiGo,
  SiGooglecloud,
  SiHelm,
  SiJunit5,
  SiKubernetes,
  SiNextdotjs,
  SiRedux,
  SiRust,
  SiSolidity,
  SiTailwindcss,
  SiTerraform,
  SiTypescript,
} from 'react-icons/si';

export const Icons = {
  sun: FaSun,
  moon: FaMoon,
  arrowRight: FaArrowRight,
  download: FaDownload,
  preview: FaExternalLinkAlt,
  githubOutline: FaGithub,
  briefcase: FaBriefcase,
  chevronDown: FaChevronDown,
  star: FaStar,
  calendar: FaCalendarAlt,
  building: FaBuilding,
  mail: FaEnvelope,
  mapPin: FaMapMarkerAlt,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaXTwitter,
  html: FaHtml5,
  css: FaCss3Alt,
  tailwind: SiTailwindcss,
  javascript: FaJs,
  typescript: SiTypescript,
  react: FaReact,
  redux: SiRedux,
  node: FaNodeJs,
  nextjs: SiNextdotjs,
  docker: FaDocker,
  java: FaJava,
  python: FaPython,
  go: SiGo,
  rust: SiRust,
  solidity: SiSolidity,
  sql: FaDatabase,
  unix: FaTerminal,
  git: FaGitAlt,
  kubernetes: SiKubernetes,
  helm: SiHelm,
  aws: SiAwslambda,
  gcp: SiGooglecloud,
  cicd: SiGithubactions,
  junit: SiJunit5,
  terraform: SiTerraform,
  c: SiC,
  cpp: SiCplusplus,
  csharp: SiDotnet,
};
